### PR TITLE
upgrade to RPR 3.1

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by asinghvi17** [comment]
What's the link to these files?  If we can redistribute them (I presume so), we could upload them as a tarball to a Github release on RadeonProRender.jl, and download that as an artifact.  I'm not sure how we could refer to the files though - that might need a `deps/build.jl` step.

**Comment by Astro-mh** [comment]
For this release at least, macOS doesn't need the hipbin files, so it would be quite nice to have those files selectively installed by the artifacts system rather than being part of the standard Julia package.

**Comment by SimonDanisch** [comment]
If you can make a pr to use the artifact system I'm happy to merge it ;)

**Comment by asinghvi17** [comment]
VolumeMaterial isn't defined anywhere @SimonDanisch?

**Comment by asinghvi17** [comment]
I got this working with artifacts locally, but seem to be having some trouble uploading them.  If I can get that done tonight, will open a PR.

I'm trying to get them to a gist so we can at least use them temporarily, but once we release, I'd like to put the hipbin files as an extra tarball within the release, so we can easily upgrade.

**Pull request merged**
